### ISSUE TITLE
Dać możliwość robienia walnego online

### ISSUE THREAD

**Issue by d33tah** [hakierspejs/statut#12]

**Comment by ghost** [comment]
Póki nie wymyślimy, jak to bezpiecznie zrobić, póty ja jestem na nie.
edit:
Piszę o głosowaniu. Bierny udział chyba nie jest żadnym problemem.

**Comment by d33tah** [comment]
@kujaw dopóki nie będzie to głosowanie tajne, wystarczy mumble. W przypadku głosowania tajnego i tak potrzeba jednej zaufanej osoby, żeby liczyła głosy - równie dobrze można wtedy do niej wysyłać SMS.

**Comment by ghost** [comment]
W sumie racja. Dopóki jest jawne, to wygląda na to, że da się zrobić.

**Comment by kpc21** [comment]
Jest możliwość i przed Covidem była. Opisałem wszystko na forum – tutaj nie będę się powielać. Generalnie – TRZEBA mieć to wpisane w statut (chwilowo tylko nie trzeba, bo Covid). To znaczy nie do końca, ale przy naszym szkicu w obecnej formie ono by nie przeszło. Zrobiłem też ankietę.

Co do głosowania – jawne bez problemu, tajne – też da się ogarnąć, czy to przez jakiś ogarnięty wewnętrznie skrypt (raczej niezalecane, bo jak ktoś z członków będzie chciał narobić nam problemów, to będzie mu łatwiej je nam narobić, trzeba będzie udowadniać przed sądem, że system do głosowania nie oszukuje), czy przez zewnętrzny system, który będzie pozwalał na jednorazowe głosowanie po wejściu w indywidualny link.

Cytując osobę, która mi doradzała:
> Tylko trzeba znaleźć usługę która ma pewne gwarancje dot. Liczenia głosów i prawidłowości w umowie licencyjnej/świadczenia usługi

**Comment by kpc21** [comment]
możliwość dana
