### ISSUE TITLE
Słownictwo: zdecydować się na "składkę członkowską" albo "miesięczną składkę"

### ISSUE THREAD

**Issue by d33tah** [hakierspejs/statut#22]

**Comment by d33tah** [comment]
Wszystko jedno które, byleby jedno wybrać.

**Comment by d33tah** [comment]
@olewales powiedział, że lepiej brzmi "składka członkowska", bo wtedy jeśli zdecydujemy się np. na tygodniową, to nie musimy zmienić statutu

**Comment by pmysl** [comment]
Wygrała składka członkowska
