### ISSUE TITLE
Działalność gospodarcza: czy musimy to wywalić ze statutu, żeby uniknąć rachunkowości pełnej?

### ISSUE THREAD

**Issue by d33tah** [hakierspejs/statut#23]

**Comment by kpc21** [comment]
Działalność gospodarcza ogranicza nam swobodę w kwestii lokali miejskich. Nie jakoś bardzo, ale do pewnego stopnia tak.

**Comment by kpc21** [comment]
> Art. 10a. 1. Organizacje pozarządowe, z wyłączeniem spółek kapitałowych,
> oraz podmioty wymienione w art. 3 ust. 3 pkt 2 prowadzą uproszczoną ewidencję
> przychodów i kosztów, w przypadku gdy:
> 1) działają w sferze zadań publicznych określonych w art. 4 ust. 1,
> 2) **nie prowadzą działalności gospodarczej w rozumieniu przepisów ustawy z dnia**
> **6 marca 2018 r. – Prawo przedsiębiorców,**
> 3) nie posiadają statusu organizacji pożytku publicznego,
> 4) osiągają przychody wyłącznie z:
> a) działalności nieodpłatnej pożytku publicznego z tytułu składek
> członkowskich, darowizn, zapisów, spadków, dotacji, subwencji,
> przychodów pochodzących z ofiarności publicznej,
> b) działalności odpłatnej pożytku publicznego z tytułu sprzedaży towarów
> i usług,
> c) tytułu sprzedaży, najmu lub dzierżawy składników majątkowych,
> d) tytułu odsetek od środków pieniężnych na rachunkach bankowych lub
> rachunkach w spółdzielczych kasach oszczędnościowo-kredytowych,
> prowadzonych w związku z wykonywaną działalnością, w tym także
> odsetek od lokat terminowych oraz innych form oszczędzania,
> przechowywania lub inwestowania, tworzonych na tych rachunkach,
> 5) w roku poprzedzającym rok wyboru prowadzenia uproszczonej ewidencji
> przychodów i kosztów osiągnęły przychody wyłącznie z tytułów, o których
> mowa w pkt 4, w wysokości nieprzekraczającej 100 000 zł
> – jeżeli decyzję w sprawie prowadzenia uproszczonej ewidencji przychodów
> i kosztów podejmie organ zatwierdzający w rozumieniu przepisów o rachunkowości.

Odpowiedź brzmi: **TAK, musimy**.

**Comment by d33tah** [comment]
@kpc21 napisałbyś pull requesta żeby to usunąć?

**Comment by kpc21** [comment]
działalność usunięta
