### ISSUE TITLE
Pytanie: jaki jest default, jeśli w statucie nie podano sposobu informowania członków o walnym?

### ISSUE THREAD

**Issue by d33tah** [hakierspejs/statut#25]

**Comment by d33tah** [comment]
Luźna propozycja: każdy musi być informowany przy pomocy przynajmniej dwóch członków

**Comment by d33tah** [comment]
To musi być w statucie, czy może być w uchwałach?

**Comment by kpc21** [comment]
Chyba nie ma defaulta.

https://poradnik.ngo.pl/walne-zebranie-czlonkow-stowarzyszenia

> Wszystkie zasady zwoływania walnego zebrania członków powinny zostać określone w statucie stowarzyszenia i uwzględniać:
> 
> częstotliwości zebrań,
> organ zobowiązany do ich zwoływania,
> sposób powiadamiania członków,
> podmioty uprawnione do wnioskowania o zwołanie nadzwyczajnego walnego zebrania członków, oraz
> ewentualne konsekwencje wynikające z niedopełnienia obowiązków, w którymś z powyższych zakresów.

**Comment by ghost** [comment]
We wszystkich statutach, które widziałem, jest określony środek informowania członków o walnym.

**Comment by kpc21** [comment]
Zrobiłem PR#30 do statutu z zawiadamianiem mailem.

**Comment by kpc21** [comment]
PR zmerdżowany wczoraj. W związku z tym chyba można zamknąć to "iszju".
