### ISSUE TITLE
Wydzielenie zmiennych ze statutu do regulaminów/uchwał

### ISSUE THREAD

**Issue by olewales** [hakierspejs/statut#27]
Tyczy się to wszystkich miejsc gdzie w statucie pojawiają się jakieś konkretne liczby ale moją uwage przykuł ten fragment:

`b) upoważniony jest każdy członek zarządu działający samodzielnie, jeżeli wysokość podejmowanego zobowiązania nie przekracza 128 PLN jednorazowo lub 512 PLN łącznie w czasie trwania jednego miesiąca.`

Jako że statut może się zmieniać wolniej niż siła nabywcza złotówki sugeruję takie rzeczy wydzielić do jakiegoś osobnego dokumentu, który możemy aktualizować częściej a w statucie napisać coś w stylu "... nie przekracza kwoty określonej uchwałą"

**Comment by kpc21** [comment]
Przegłosowane i dodane do statutu, aczkolwiek pojawiły się kontrowersje – najlepiej do przedyskutowania z prawnikiem. Okazuje się, że do KRS-u wpisuje się sposób reprezentacji stowarzyszenia przez zarząd, i jak nie będziemy mieć wpisanej konkretnej maksymalnej kwoty zobowiązania do statutu, może być tak, że np. bank będzie nam robił problemy z ustaleniem limitów na kartę płatniczą. Nie wiem, na ile to faktycznie jest poważne i zdarza się, ale HS-Krk poinformował nas o możliwości takiej sytuacji.

**Comment by d33tah** [comment]
@olewales zamykam to po dłuższej dyskusji. Daj znać, jeśli uważasz że jest sens robić reopen.
