### ISSUE TITLE
Wydłużyć kadencję zarządu?

### ISSUE THREAD

**Issue by d33tah** [hakierspejs/statut#37]
Cytująć panią z OPUS:

> czy świadomie wpisaliście,  że kadencja wszystkich władz trwa rok? czy to nie za krótko? bo z jednej strony zarząd nie zdąży jeszcze rozwinąć skrzydeł a juz minie rok i będą kolejne wybory. oczywiście te same osoby mogą zostać ponownie wybrane do zarządu, ale tez każda zmiana chociaż jednej osoby w zarzadzie bądz komisji rewizyjnej sprawia, że do sądu trzeba wysłać odpowiednie informacje o zmianie osoby.

Kontekst: https://pad.hs-ldz.pl/lTfC8SwXRZmp6diGc2A2sg

**Comment by ksiezak** [comment]
Może jednak by wrócić do 2 letniej kadencji, jak było pierwotnie i walnych zwyczajnych co dwa lata (o ile tak było)? Jeśli dla Ciebie osobiście to za długo, to jeśli w zarządzie pozostaną 2 osoby, to mogą dobrać trzecią metodą kooptacji według regulaminu, więc nie będzie to wymagało zebrania nadzwyczajnego. 

Można się też nieformalnie umówić, że te 2 osoby wybiorą trzecią, na podstawie głosowania elektronicznego reszty członków.
