### ISSUE TITLE
Określić kwoty, do której zarząd może podpisywać samodzielnie

### ISSUE THREAD

**Issue by d33tah** [hakierspejs/statut#38]
Cytując panią z OPUS:

> zwyczajowo w statucie określało się tą kwotę do której członek zarządu może podpisywać samodzielnie. Bo jest to z reguły bardziej praktyczne. Np jesli każda instytucje będzie od Was wymagala zapisów jak wygląda u Was kwestia podpisywania, to wowczas zawsze oprócz statutu będziecie musieli posyłać tą aktualną uchwałę Zarządu. MOże być również sytuacja, że jakaś instytucja uzna, że taka uchała powinna być sporządzona notarialnie, a więc wówczas może być to dla Was kłopot i dodatkowy wydatek. Zastanówcie się czy jednak nie znajdziecie takiej kwoty, którą od razu jesteście w stanie ustalić i wpisać do statutu.

Kontekst: https://pad.hs-ldz.pl/lTfC8SwXRZmp6diGc2A2sg

**Comment by ksiezak** [comment]
Usunęliśmy te kwoty, by statut był "odporny" na hiperinflację. Może warto by spytać, czy nie można tego w statucie ująć tak, że zarząd może wydawać do X zł według siły nabywczej z 2020, liczonej według danych GUS, albo jakoś tak. Albo się w to nie bawić i w przypadku hiperinflacji po prostu zrobić update.
