### ISSUE TITLE
Usunąć cykliczność w kompetencjach walnego

### ISSUE THREAD

**Issue by d33tah** [hakierspejs/statut#42]
"Do kompetencji Walnego Zebrania Członków należą: [...] c) wybór i odwoływanie wszystkich władz Stowarzyszenia," // "Władzami Stowarzyszenia są: a) Walne Zebranie Członków," // rekomenduję doprecyzować bo się zapętlamy, walne nie może wybierać walnego

**Comment by bell0x07** [comment]
Proponuję we wszystkich miejscach gdzie nie ma mowy o wszystkich władzach stowarzyszenia wymienić po prostu o które chodzi, władze na ten moment byłyby trzy, więc nie ma co komplikować.
