### ISSUE TITLE
Sprawdzić czy stowarzyszenie musi zawierać słowo "Stowarzyszenie" w nazwie

### ISSUE THREAD

**Issue by d33tah** [hakierspejs/statut#44]
(czy tam na początku)

**Comment by bell0x07** [comment]
"W przypadku stowarzyszenia, które będzie prowadzić działalność gospodarczą, w nazwie powinna zostać wskazana forma prawna organizacji, czyli musi być użyte słowo „stowarzyszenie” (art. 43 Kodeksu cywilnego)."

za: https://poradnik.ngo.pl/co-musi-zawierac-statut-stowarzyszenia
